# Cấu hình Website 1
server {
    listen 80;
    server_name domain1.local;

    location / {
        root /usr/share/nginx/html/site1;
        index index.html;
    }
}

# Cấu hình Website 2
server {
    listen 80;
    server_name domain2.local;

    location / {
        root /usr/share/nginx/html/site2;
        index index.html;
    }

    # Proxy hỗ trợ cho Bài tập 2 (Gọi API Node-RED qua Nginx)
    location /api/ {
        proxy_pass http://web_nodered:1880/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
